import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import Navbar from "@/components/Navbar";
import Marquee from "@/components/Marquee";
import Footer from "@/components/Footer";
import { Suspense } from "react";

const notoSrifBenglai = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSrifBenglai.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header />
        <Suspense fallback={null}>
          <Navbar />
        </Suspense>
        <Suspense fallback={null}>
          <Marquee />
        </Suspense>
        <Suspense fallback={null}>
          <main className="container mx-auto">{children}</main>
        </Suspense>
        <Footer/>
      </body>
    </html>
  );
}
