import type { Metadata } from "next";
import { Noto_Serif_Bengali } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";import Navbar from "@/components/Navbar";
;
// import Marquee from "@/components/Marquee";

const notoSrifBenglai = Noto_Serif_Bengali({
  subsets: ["latin", "bengali"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      data-theme="light"
      className={`${notoSrifBenglai.className} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col">
        <Header/>
        <Navbar/>
        {/* <Marquee/> */}
        <main className="max-w-7xl mx-auto">
          {children}
        </main>
        </body>
    </html>
  );
}
